TMUX_DIR="$HOME/.config/tmux"

set -g default-terminal "tmux-256color"
set -g extended-keys on
set -as terminal-features ",kitty:RGB"

set -s escape-time 0

set -g status-position top
set -g prefix C-a
set -g base-index 1
set -g mouse on
set -g display-panes-time 4000
set -g status-justify centre
set -g visual-activity on
set -g allow-passthrough on
set -g renumber-windows on
set -g history-limit 50000
set -g detach-on-destroy off
set -g focus-events on

setw -g pane-base-index 1
setw -g monitor-activity on
setw -g mode-keys vi

unbind C-b

bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H previous-window
bind L next-window
bind S switch-client -l
bind C-H swap-pane -t '{left-of}'
bind C-J swap-pane -t '{down-of}'
bind C-K swap-pane -t '{up-of}'
bind C-L swap-pane -t '{right-of}'
bind & kill-window
bind r source-file "$TMUX_DIR/tmux.conf" \; display "conf reloaded"

bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2

bind -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi v      send-keys -X begin-selection
bind -T copy-mode-vi y      send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi p      send-keys -X copy-selection-and-cancel \; paste-buffer

# Lazy load
bind C-s run-shell "$TMUX_DIR/scripts/lazy-resurrect"

set-hook -g session-created {
    if-shell -F '#{==:#{session_name},0}' { rename-session 1 }
}

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-notify'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'joshmedeski/tmux-fzf-url'

set -g @tmux_power_theme 'colour5'
set -g @tmux_power_right_arrow_icon ''
set -g @tmux_power_left_arrow_icon  ''
set -g @tmux_power_left_a '#{tmux_mode_indicator}'
set -g @tmux_power_left_b ''
set -g @tmux_power_right_y ' #S'
set -g @tmux_power_right_z ' #{USER}@#h'

set -g @mode_indicator_prefix_mode_style 'bg=green,fg=black'

set -g @mode_indicator_copy_mode_style 'bg=cyan,fg=black'

set -g @mode_indicator_empty_mode_style 'bg=bright-black,fg=bright-black'

set -g @continuum-save-interval '30'
set -g @continuum-restore 'off'

run "$TMUX_DIR/plugins/tpm/tpm"
