VISUAL=$XDG_BIN_HOME/nvim
EDITOR=$VISUAL
SUDO_EDITOR=$VISUAL
DOAS_EDITOR=$VISUAL
GIT_EDITOR=$VISUAL

PAGER=ov
MANROFFOPT=-c

SYSTEMD_EDITOR=$VISUAL
SYSTEMD_COLORS=false
SYSTEMD_PAGERSECURE=true
SYSTEMD_PAGER=$PAGER

XCOMPOSEFILE=$XDG_CONFIG_HOME/X11/xcompose
GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc
WGETRC=$XDG_CONFIG_HOME/wgetrc
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
PARALLEL_HOME=$XDG_CONFIG_HOME/parallel
RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/ripgrep/.ripgreprc

GNUPGHOME=$XDG_DATA_HOME/gnupg
CARGO_HOME=$XDG_DATA_HOME/cargo
RUSTUP_HOME=$XDG_DATA_HOME/rustup
GOPATH=$XDG_DATA_HOME/go

NUGET_PACKAGES=$XDG_CACHE_HOME/NuGetPackages

LESSHISTFILE=$XDG_STATE_HOME/less/history

KUBE_EDITOR=$VISUAL

FX_THEME=2

OPENAI_API_KEY=lm-studio

POSTING_PAGER_JSON=fx

STOW_DIR=$HOME/dotfiles

PROTON_PASS_LINUX_KEYRING=dbus
