GOPATH=$XDG_DATA_HOME/go

VISUAL=$HOME/.local/bin/nvim
EDITOR=$VISUAL
SUDO_EDITOR=$VISUAL
DOAS_EDITOR=$VISUAL
GIT_EDITOR=$VISUAL

SYSTEMD_EDITOR=$VISUAL
SYSTEMD_COLORS=false
SYSTEMD_PAGERSECURE=true
SYSTEMD_PAGER=bat --language syslog --plain

PAGER=ov
MANROFFOPT=-c

KUBE_EDITOR=$VISUAL

FX_THEME=2

RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep/.ripgreprc

OPENAI_API_KEY=lm-studio

POSTING_PAGER_JSON=fx

STOW_DIR=$HOME/dotfiles
