XDG_DATA_HOME=$HOME/.local/share
XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache

GOPATH=$HOME/.local/share/go

VISUAL=nvim
EDITOR=nvim
SUDO_EDITOR=nvim
DOAS_EDITOR=nvim
GIT_EDITOR=nvim
PAGER=moor
MANROFFOPT=-c
SYSTEMD_PAGER=bat -l syslog

# moor
MOOR=-colors=auto -terminal-fg

# k9s
KUBE_EDITOR=nvim

# fx
FX_THEME=2

# rg
RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep/.ripgreprc

# LM Studio
OPENAI_API_KEY=lm-studio

# Posting
POSTING_PAGER_JSON=fx

# Stow
STOW_DIR=$HOME/dotfiles
