XDG_DATA_HOME=$HOME/.local/share
XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache

GOPATH=$XDG_DATA_HOME/go

VISUAL=$HOME/.local/bin/nvim
EDITOR=$VISUAL
SUDO_EDITOR=$VISUAL
DOAS_EDITOR=$VISUAL
GIT_EDITOR=$VISUAL
SYSTEMD_EDITOR=$VISUAL
SYSTEMD_PAGER=bat -l syslog
PAGER=moor
MANROFFOPT=-c

# moor
MOOR="--colors=auto --terminal-fg"

# k9s
KUBE_EDITOR=$VISUAL

# fx
FX_THEME=2

# rg
RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep/.ripgreprc

# LM Studio
OPENAI_API_KEY=lm-studio

# Posting
POSTING_PAGER_JSON=fx

# Stow
STOW_DIR=$HOME/dotfiles
