general {
  inhibit_sleep = 2
}

listener {
  timeout = 1
  on-timeout = :
  on-resume = screensaver-stop
  condition_cmd = systemctl --user --quiet is-active screensaver.service
}

# 2.5 min
listener {
  timeout = 150
  on-timeout = sunsetr preset idle
  on-resume = sunsetr preset default
}

# 3.5 min
listener {
  timeout = 210
  on-timeout = screensaver-start
}

### AFTER the screensaver since it resets the timer ###

# 5 min
listener {
  timeout = 90
  on-timeout = loginctl lock-session
  condition_cmd = systemctl --user --quiet is-active screensaver.service
}

### AFTER lock-session since it resets the timer ###

# 5.5 min
listener {
  timeout = 30
  on-timeout = sunsetr preset idle && brilloctl idle
  on-resume = sunsetr preset default && brilloctl unidle
  condition_cmd = systemctl --user --quiet is-active lock.target
}

# 6 min
listener {
  timeout = 60
  on-timeout = system-suspend
  condition_cmd = systemctl --user --quiet is-active lock.target
}
