general {
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
  inhibit_sleep = 2
}

listener {
  timeout = 1
  on-resume = screensaver-video-stop
}

# 2.5 min
listener {
  timeout = 150
  on-timeout = sunsetr preset idle
  on-resume = sunsetr preset default
}

# 3.5 min
listener {
  timeout = 210
  on-timeout = screensaver-video-start && sunsetr preset default
}

### AFTER the screensaver since it resets the timer ###

# 5 min
listener {
  timeout = 90
  on-timeout = pgrep -x murale && loginctl lock-session
}

### AFTER lock-session since it resets the timer ###

# 5.5 min
listener {
  timeout = 30
  on-timeout = pgrep -x hyprlock && sunsetr preset idle
  on-resume = pgrep -x hyprlock && sunsetr preset default
}

# 6 min
listener {
  timeout = 60
  on-timeout = pgrep -x hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = pgrep -x hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# 6.5 min
listener {
  timeout = 90
  on-timeout = pgrep -x hyprlock && systemctl suspend
}
