# Float and center
windowrule = size 845 800, match:tag floating-window
windowrule = tag +floating-window, match:class (kitty.tui.float)

# Clipse
windowrule = float on, match:class clipse
windowrule = size 622 652, match:class (clipse)

# mpv
windowrule = tag -floating-window*, match:class mpv
windowrule = float on, center on, size 875 600, match:class mpv

# localsend
windowrule = size 445 700, match:class localsend

# Workspaces
windowrule = workspace 1, match:class gaming-log
windowrule = workspace 3, match:class (tidal-hifi|luna)
windowrule = workspace 4, match:class gamescope
windowrule = workspace 5, match:class equibop
windowrule = workspace 5, match:class streamlink-twitch-gui
windowrule = workspace 5, match:class steam

# https://github.com/basecamp/omarchy/discussions/3052
# Screen-sharing indicator
windowrule = tag +screen-share-indicator, match:title ^(.*is sharing.*\.)$
windowrule = float on, match:tag screen-share-indicator
windowrule = border_size 0, match:tag screen-share-indicator
# Pin to bottom-right corner
windowrule = move (monitor_w-window_w-20) (monitor_h-window_h-20), match:tag screen-share-indicator
windowrule = pin on, match:tag screen-share-indicator
