ctrl_n_shortcuts = true
enter_accept = true
history_filter = [
  "^ga$",
  "^glo$",
  "^grb$",
  "^gwr$",
  "^gws$",
  "^git reset",
  "^git push secret",
  "^man",
  "^gpf$",
  "^sudo",
  "^sc-",
  "^scu-",
  "^vim$",
  "^nvim$",
]
inline_height = 10
keymap_mode = "vim-normal"
style = "compact"
sync_frequency = "168h"

[theme]
name = "rose-pine"

[sync]
records = true
