ctrl_n_shortcuts = true
enter_accept = true
history_filter = [
  "^g(a|lo|rb|pf)$",
  "^gd(\\s--staged)?$",
  "^gw(r|s)$",
  "^git reset",
  "^git push secret",
  "^man",
  "^(sudo|doas)(edit)?",
  "^scu?-",
  "^n?vim$",
  "^(a|p)sd ",
  "^z ",
  "^uuctl$",
  "^update$",
  "^paru(i)?(\\s-Ss)?",
  "^md5sum ",
  "^secret-tool",
  "^yazi",
  "^pac((?i)u|x|i)(?-i)",
]
inline_height = 10
keymap_mode = "vim-normal"
style = "compact"
sync_frequency = "168h"

[theme]
name = "rose-pine"

[sync]
records = true
