#:schema https://yazi-rs.github.io/schemas/theme.json

[flavor]
light = "rose-pine-dawn"
dark = "rose-pine"

[git]
unknown_sign = ""
untracked_sign = "?"
modified_sign = ""
deleted_sign = ""
clean_sign = ""
deleted = { fg = "red", bold = true }
