#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
show_hidden = true
sort_by = "natural"
linemode = "size_and_mtime"

[input]
cursor_blink = true

[plugin]
prepend_previewers = [
  # ouch
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },

  # mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },

  # DuckDB
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },

  # piper
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow --style=tokyo-night --width=0 "$1"' },
  { url = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes --follow-symlinks --all "$1"' },
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]

prepend_fetchers = [{ url = "*/", run = "git", group = "git" }]

[opener]
open = [{ run = 'open %s', orphan = true, desc = "Open", for = "unix" }]
extract = [
  { run = 'ouch d -y %s', desc = "Extract here with ouch", for = "unix" },
]

[tasks]
image_alloc = 1073741824
