---
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  exitMessage:
    display: false
  mods:
    clocks_a:
      colors:
        rows:
          even: lightblue
          odd: white
      enabled: true
      locations:
        CDMX: America/Mexico_City
        UTC: Etc/UTC
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: alphabetical
      title: America
      type: clocks
    clocks_b:
      colors:
        rows:
          even: lightblue
          odd: white
      enabled: true
      locations:
        Paris: Europe/Paris
        Barcelona: Europe/Madrid
        Dubai: Asia/Dubai
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: alphabetical
      title: Europe
      type: clocks
    ipinfo:
      colors:
        name: lightblue
        value: white
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 150
    feedreader:
      title: RSS
      enabled: true
      focusable: true
      feeds:
        - https://terminaltrove.com/new.xml
        - https://news.ycombinator.com/rss
        - https://www.jornada.com.mx/rss/edicion.xml
      feedLimit: 10
      position:
        top: 1
        left: 0
        width: 4
        height: 3
      refreshInterval: 18000
  navigation:
    shortcuts: false
  term: xterm-256color
