[widget.control-center]
custom_image = "~/.local/share/icons/hicolor/scalable/apps/cachyos-linux.svg"

[widget.workspaces]
active_pill_size = 1.0
hide_when_empty = true
focused_color = "secondary"
occupied_color = "surface_variant"

[widget.clock]
format = "{:L%a %d %h %I:%M %p}"
font_family = "Zalando Sans"
scale = 0.9

[widget.volume]
show_label = false
mute_color = "#6e6a86" # @muted

[widget.tray]
drawer = true
drawer_columns = 5
hide_passive = true
detached_panel = true

[widget.weather]
show_condition = false
show_temperature = false

[widget.privacy]
hide_inactive = true
capsule = true
capsule_fill = "#D20F39" # catppuccin red
capsule_opacity = 0.9
capsule_padding = 15
active_color = "#E0DEF4" # @text
inactive_color = "error"

[widget.notifications]
hide_when_no_unread = true

[widget.media]
title_scroll = "on_hover"
hide_when_no_media = true

[widget.taskbar]
show_active_indicator = false
inactive_opacity = 0.6
