[plugins]
enabled = [
  "noctalia/screen_recorder",
  "marccvictoria/llamanager",
  "nightwatch75/file-search",
  "lucasoe/proton-pass",
]
auto_update = true

[plugin_settings."noctalia/screen_recorder"]
color_range = "full"
directory = "~/Vídeos"
video_codec = "hevc"
hide_inactive = true

[plugin_settings."marccvictoria/llamanager"]
launcher = "qwen3.5:9b-q4_K_M"

[plugin_settings."nightwatch75/file-search"]
show_hidden = true
