[widget.control-center]
glyph = ""
custom_image = "~/.local/share/icons/hicolor/scalable/apps/cachyos-linux.svg"
custom_image_colorize = true

[widget.workspaces]
active_pill_size = 1.0
hide_when_empty = true
occupied_color = "surface_variant"

[widget.clock]
format = "{:L%a %d %h %I:%M %p}"
font_family = "Zalando Sans"
scale = 0.9

[widget.volume]
show_label = false

[widget.brightness]
show_label = false

[widget.tray]
drawer = true
drawer_columns = 5

[widget.weather]
show_condition = false
show_temperature = false

[widget.privacy]
hide_inactive = true

[widget.notifications]
hide_when_no_unread = true
