[tools]
assh = "latest"
bat = "latest"
bun = "latest"
colima = "latest"
delta = "latest"
docker-cli = "latest"
docker-compose = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
gh = "latest"
gitleaks = "latest"
glow = "latest"
go = "latest"
gomigrate = "latest"
grpcurl = "latest"
grype = "latest"
htmlq = "latest"
jj = "latest"
k9s = "latest"
kompose = "latest"
lazydocker = "latest"
lazygit = "latest"
lima = "latest"
mkcert = "latest"
mockery = "latest"
neovim = "nightly"
node = "lts"
"pipx:posting" = "latest"
protobuf = "latest"
protoc-gen-grpc-web = "latest"
protoc-gen-js = "latest"
python = "latest"
ripgrep = "latest"
ripsecrets = "latest"
steampipe = "latest"
uv = "latest"
viddy = "latest"
vivid = "latest"
xh = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
"pipx:pgcli" = "latest"
"pipx:tldr" = "latest"

[settings]
experimental = true
