[tools]
assh = "latest"
bat = "latest"
bun = "latest"
delta = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
gh = "latest"
gitleaks = "latest"
glow = "latest"
go = "latest"
gomigrate = "latest"
grpcurl = "latest"
grype = "latest"
htmlq = "latest"
jj = "latest"
k9s = "latest"
kompose = "latest"
lazydocker = "latest"
lazygit = "latest"
lima = "latest"
mkcert = "latest"
mockery = "latest"
neovim = "nightly"
node = "lts"
ripgrep = "latest"
ripsecrets = "latest"
steampipe = "latest"
viddy = "latest"
vivid = "latest"
xh = "latest"
zellij = "latest"
zoxide = "latest"
trivy = "latest"
fastfetch = "latest"
dbmate = "latest"
cosign = "latest"
eza = "latest"
rclone = "latest"
kubeconform = "latest"
minikube = "latest"
act = "latest"
age = "latest"
task = "latest"
cargo-binstall = "latest"
mitmproxy = "latest"
"pipx:posting" = "latest"
"pipx:pgcli" = "latest"
"pipx:tldr" = "latest"
"pipx:rich-cli" = "latest"
shellcheck = "latest"
buf = "latest"
yazi = "latest"
btop = "latest"
docker-slim = "latest"
jc = "latest"
dua = "latest"
duckdb = "latest"
golangci-lint = "latest"
lnav = "latest"

[settings]
experimental = true
